### ISSUE TITLE
The Final Roadmap to the git Introduction

### ISSUE THREAD

**Issue by coco33920** [neo-schobert/hello_world_python#1]
- [X] Base de la base
- [ ] contrôle de connaissances
- [ ] how to coder à plusieurs the ultimate way to do that
